[versions]
minestom = "2025.10.31-1.21.10" # https://mvnrepository.com/artifact/net.minestom/minestom-snapshots
logback = "1.5.21" # https://github.com/qos-ch/logback/releases
blocksandstuff = "1.9.0-SNAPSHOT" # https://mvn.everbuild.org/#/public/org/everbuild/blocksandstuff
#loot-tables = "3.0" # https://github.com/GoldenStack/trove/releases
#minestom-fluids = "48ccf450d8"

[libraries]
minestom = { group = "net.minestom", name = "minestom", version.ref = "minestom" }
logback = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }
blocks = { group = "org.everbuild.blocksandstuff", name = "blocksandstuff-blocks", version.ref = "blocksandstuff"}
fluids = { group = "org.everbuild.blocksandstuff", name = "blocksandstuff-fluids", version.ref = "blocksandstuff"}
#minestom-fluids = { group = "com.github.TogAr2", name = "MinestomFluids", version.ref = "minestom-fluids"}
#loot-tables = { group = "net.goldenstack", name = "trove", version.ref = "loot-tables" }

[bundles]
server = ["minestom", "logback", "blocks", "fluids"]